<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Atau_password</name>
   <tag></tag>
   <elementGuidId>c34ced5b-2ed8-48b6-aa1b-aff60871f844</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='password'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f60a9e49-f3b3-4a69-8980-f9d2b6e9ac02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kata kunci</value>
      <webElementGuid>6c569a85-3e9d-47b9-bb1f-3bedc941324a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>897d11de-c37f-4df6-8aed-b23bbf7bcc83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d29221cb-b096-4a42-ba63-a4f10804f673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>@</value>
      <webElementGuid>035162cd-5ddc-495d-95be-2efa666b13c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;dimmable dimmed&quot;]/div[@class=&quot;ui page modals dimmer transition visible active&quot;]/div[@class=&quot;ui mini modal transition visible active&quot;]/div[@class=&quot;content&quot;]/div[1]/div[@class=&quot;ui center aligned middle aligned grid&quot;]/div[@class=&quot;column&quot;]/div[3]/form[@class=&quot;ui large form&quot;]/div[@class=&quot;ui segment&quot;]/div[2]/div[@class=&quot;field&quot;]/div[@class=&quot;ui fluid left icon input&quot;]/input[1]</value>
      <webElementGuid>d39c4194-583a-447b-a96f-5ba53de5a3ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='password'])[2]</value>
      <webElementGuid>66bdbc45-ee20-4ccb-af03-3e1091139b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/div[3]/form/div/div[2]/div/div/input</value>
      <webElementGuid>864a8621-5e83-4532-802b-59304d727583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Kata kunci' and @name = 'password' and @type = 'password']</value>
      <webElementGuid>b6130390-aa89-4193-8e75-7f305d29048d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
