<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Atau_username</name>
   <tag></tag>
   <elementGuidId>31fd10fb-4f20-4867-a9a6-035c92ea8a8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='username'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>19980873-71a3-402f-8ba5-97562d88c10d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email atau nama pengguna</value>
      <webElementGuid>0a33bfff-c017-4390-9280-2911dfde4dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>af1721dc-bd77-4eb1-976f-1f3feb8e3310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c3954834-384b-447c-b83b-9e28402ea5b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;dimmable dimmed&quot;]/div[@class=&quot;ui page modals dimmer transition visible active&quot;]/div[@class=&quot;ui mini modal transition visible active&quot;]/div[@class=&quot;content&quot;]/div[1]/div[@class=&quot;ui center aligned middle aligned grid&quot;]/div[@class=&quot;column&quot;]/div[3]/form[@class=&quot;ui large form&quot;]/div[@class=&quot;ui segment&quot;]/div[1]/div[@class=&quot;field&quot;]/div[@class=&quot;ui fluid left icon input&quot;]/input[1]</value>
      <webElementGuid>b5cbc658-4f26-4435-a207-7c0415222037</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='username'])[2]</value>
      <webElementGuid>9e0074c5-3a1b-41c5-b01d-263466aa035a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/div[3]/form/div/div/div/div/input</value>
      <webElementGuid>a222c6b2-e497-4f8e-a151-98d21f6d3de2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Email atau nama pengguna' and @name = 'username' and @type = 'text']</value>
      <webElementGuid>b06f4fcf-c84d-40ba-a6a1-39e4292fd43e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
