<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_GueTbOalGd baruTBmfY maumRrnOYohU meningg_2314dd</name>
   <tag></tag>
   <elementGuidId>937913a1-5219-4ceb-9d9c-f754d79b08f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='reading-wrapper']/div/div/div[2]/div/div/p[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d55e32f2-9dfe-4744-97c1-75d666d21ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ql-align-justify</value>
      <webElementGuid>bce72e18-43bf-4b98-a229-b327714d4b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GueTbOalGd baruTBmfY maumRrnOYohU meninggalkanYTAEk kamarXCWmYz hotelYLWUz ketikaiHsBjeA teringatnIxXwc perempuanbpRj yangVuW tertidurEPescVywG dihrK dalamISBcNEnQrD kamarGNqHXxQ itu.QgbkEqmA NggakrUTsnXbIY apa-apakIHFOBDdVo kalauUsdRNHj guegME meninggalkanvVMcgJdUth diarlK begituKSw saja,wYECLxT kan?XCJYEGZpmV Guerbgv lantasfVvWdFH menggelengkanWPsz kepalaKAvLSgu karenapeYSb memikirkansreKkcB pertanyaanmZIaSkEioU sebodohUAbDM itu.UPI SejakoDcXzwxulQ kapanVTxI gueQHWmYOUc jadivTdAtr pedulidwng padaMTg orangkpVoN lain?MgRtzjQKUZ OrangFnSKQgL asingluAfZBrd yangNaQSGrJLTR masihVrhDYsy dibuaiusRaZJ mimpirjqhAWtnuP ituVqRbFZ adalahnsABj perempuanjQLO yangynFPcJzHt pastiKFNvSUJi bisaoXsYfRuiBb bertanggungsnI jawabkQRbhV padaBrPxMmdkeU diriiBFT diaPkzZTQdmu sendiri.KEkgy TapiDph mungkinlKBDpvUR nggaknywXQvRuaL adaeTNghnUX salahnyacQaJ kalauofHCSXBnO guegsXDpyol memastikanZtFUdsArua bahwatTapgBxP apacjEdVPNMH yangPJIolgmCMy telahkAueV dilakukanhRWeLquIB teman-temanAQtHGwRxeh gueUEV semalamvdCW nggaktcxDmqlRsA berakibattcJvi terlaluknToGjibdl burukuXeJZcCVE padanya.</value>
      <webElementGuid>f5a37410-6b98-42d3-a466-d17be817ae62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reading-wrapper&quot;)/div[@class=&quot;qxstbk-0 etOVgd&quot;]/div[1]/div[@class=&quot;sc-1x7ap9e-1 iRfMCx&quot;]/div[1]/div[@class=&quot;reading-platform-content main-reading-content ql-editor&quot;]/p[@class=&quot;ql-align-justify&quot;]</value>
      <webElementGuid>ceb5a123-1c5c-4ff5-8037-d4d48304e6a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reading-wrapper']/div/div/div[2]/div/div/p[2]</value>
      <webElementGuid>1220bbc2-4869-47a0-9c47-02bc6a07db1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Senin, 8 April 2019 pukul 14.18'])[1]/following::p[2]</value>
      <webElementGuid>7360ad8a-fa08-43c6-877c-3f158daf6f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Titi Sanaria'])[1]/following::p[2]</value>
      <webElementGuid>5cfbfaa7-2ada-4809-9174-4a98ec1b6db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Gue']/parent::*</value>
      <webElementGuid>18efb3ea-5a50-49aa-8d93-20a055dd7518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/p[2]</value>
      <webElementGuid>f7dc5329-b38b-4e6e-8b60-4bc45cbaf0f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'GueTbOalGd baruTBmfY maumRrnOYohU meninggalkanYTAEk kamarXCWmYz hotelYLWUz ketikaiHsBjeA teringatnIxXwc perempuanbpRj yangVuW tertidurEPescVywG dihrK dalamISBcNEnQrD kamarGNqHXxQ itu.QgbkEqmA NggakrUTsnXbIY apa-apakIHFOBDdVo kalauUsdRNHj guegME meninggalkanvVMcgJdUth diarlK begituKSw saja,wYECLxT kan?XCJYEGZpmV Guerbgv lantasfVvWdFH menggelengkanWPsz kepalaKAvLSgu karenapeYSb memikirkansreKkcB pertanyaanmZIaSkEioU sebodohUAbDM itu.UPI SejakoDcXzwxulQ kapanVTxI gueQHWmYOUc jadivTdAtr pedulidwng padaMTg orangkpVoN lain?MgRtzjQKUZ OrangFnSKQgL asingluAfZBrd yangNaQSGrJLTR masihVrhDYsy dibuaiusRaZJ mimpirjqhAWtnuP ituVqRbFZ adalahnsABj perempuanjQLO yangynFPcJzHt pastiKFNvSUJi bisaoXsYfRuiBb bertanggungsnI jawabkQRbhV padaBrPxMmdkeU diriiBFT diaPkzZTQdmu sendiri.KEkgy TapiDph mungkinlKBDpvUR nggaknywXQvRuaL adaeTNghnUX salahnyacQaJ kalauofHCSXBnO guegsXDpyol memastikanZtFUdsArua bahwatTapgBxP apacjEdVPNMH yangPJIolgmCMy telahkAueV dilakukanhRWeLquIB teman-temanAQtHGwRxeh gueUEV semalamvdCW nggaktcxDmqlRsA berakibattcJvi terlaluknToGjibdl burukuXeJZcCVE padanya.' or . = 'GueTbOalGd baruTBmfY maumRrnOYohU meninggalkanYTAEk kamarXCWmYz hotelYLWUz ketikaiHsBjeA teringatnIxXwc perempuanbpRj yangVuW tertidurEPescVywG dihrK dalamISBcNEnQrD kamarGNqHXxQ itu.QgbkEqmA NggakrUTsnXbIY apa-apakIHFOBDdVo kalauUsdRNHj guegME meninggalkanvVMcgJdUth diarlK begituKSw saja,wYECLxT kan?XCJYEGZpmV Guerbgv lantasfVvWdFH menggelengkanWPsz kepalaKAvLSgu karenapeYSb memikirkansreKkcB pertanyaanmZIaSkEioU sebodohUAbDM itu.UPI SejakoDcXzwxulQ kapanVTxI gueQHWmYOUc jadivTdAtr pedulidwng padaMTg orangkpVoN lain?MgRtzjQKUZ OrangFnSKQgL asingluAfZBrd yangNaQSGrJLTR masihVrhDYsy dibuaiusRaZJ mimpirjqhAWtnuP ituVqRbFZ adalahnsABj perempuanjQLO yangynFPcJzHt pastiKFNvSUJi bisaoXsYfRuiBb bertanggungsnI jawabkQRbhV padaBrPxMmdkeU diriiBFT diaPkzZTQdmu sendiri.KEkgy TapiDph mungkinlKBDpvUR nggaknywXQvRuaL adaeTNghnUX salahnyacQaJ kalauofHCSXBnO guegsXDpyol memastikanZtFUdsArua bahwatTapgBxP apacjEdVPNMH yangPJIolgmCMy telahkAueV dilakukanhRWeLquIB teman-temanAQtHGwRxeh gueUEV semalamvdCW nggaktcxDmqlRsA berakibattcJvi terlaluknToGjibdl burukuXeJZcCVE padanya.')]</value>
      <webElementGuid>81016545-7689-4812-a616-5667e21477e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
