<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Bernard Batubara_ui centered fluid image</name>
   <tag></tag>
   <elementGuidId>2a47dbb6-e147-46a5-9a90-c42f2aabf940</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='app']/span/div/div[4]/div/div/div[2]/div/div/div/div/div[10]/div/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>af042561-7d37-4b50-89df-032bc0f422c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.storial.co/book_front/41984-ddd8b0e63ef6ca84d5cda56841fe05dfe32ac9d1.jpeg</value>
      <webElementGuid>1acc7cd5-f8b1-49dc-8470-b3038074fa9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui centered fluid image</value>
      <webElementGuid>ec7f36bf-308b-4b9b-8839-84a5b8cbc37a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/span[1]/div[@class=&quot;mryv-0 egIBm&quot;]/div[4]/div[@class=&quot;zmizm3-0 ckyoxs&quot;]/div[@class=&quot;reaxm0-0 jcasxG&quot;]/div[2]/div[@class=&quot;ui container&quot;]/div[1]/div[@class=&quot;ui grid storial-listing&quot;]/div[@class=&quot;five column row&quot;]/div[@class=&quot;column&quot;]/div[@class=&quot;ui centered card book-card&quot;]/a[1]/div[@class=&quot;n4rqeu-2 duEOuz&quot;]/img[@class=&quot;ui centered fluid image&quot;]</value>
      <webElementGuid>92c43be3-5877-4832-8cad-0546027cd9e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app']/span/div/div[4]/div/div/div[2]/div/div/div/div/div[10]/div/a/div/img</value>
      <webElementGuid>1591aa5f-ac25-4f9d-a6bb-e0fe4e70f50d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://cdn.storial.co/book_front/41984-ddd8b0e63ef6ca84d5cda56841fe05dfe32ac9d1.jpeg')]</value>
      <webElementGuid>ace667d5-325f-45e1-b081-40014b4464dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/a/div/img</value>
      <webElementGuid>313a5f25-7952-4b98-bdfc-20093dfbc5cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn.storial.co/book_front/41984-ddd8b0e63ef6ca84d5cda56841fe05dfe32ac9d1.jpeg']</value>
      <webElementGuid>2420c727-6bf8-4792-873e-d8f1d2b6dab6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
