<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_Dua</name>
   <tag></tag>
   <elementGuidId>faac11ab-3e17-493f-9964-3593cd72ae6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sc-1708h9t-0.hgIdxD > a > div.item > div.content > strong</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='app']/span/div/div/div/div[3]/a/div/div/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>74a8db52-d37f-40fb-a180-96519b0cd0c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Dua</value>
      <webElementGuid>ec5d6d84-10b7-4166-9d65-2cad33d1b718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/span[1]/div[1]/div[1]/div[@class=&quot;ui very relaxed list ui overlay left visible sidebar&quot;]/div[@class=&quot;sc-1708h9t-0 hgIdxD&quot;]/a[1]/div[@class=&quot;item&quot;]/div[@class=&quot;content&quot;]/strong[1]</value>
      <webElementGuid>7553cdb6-e19b-4bcb-924c-011e5974a111</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app']/span/div/div/div/div[3]/a/div/div/strong</value>
      <webElementGuid>64ca0855-29e1-420e-b9ac-6b5eb56a1bd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[1]/following::strong[2]</value>
      <webElementGuid>254caf96-65ef-4770-b322-155fdaf97002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dua']/parent::*</value>
      <webElementGuid>ca703783-40e9-4e65-b5f1-daf6ea595cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/div/div/strong</value>
      <webElementGuid>a2271600-d124-4591-a81a-499a1617b567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = ' Dua' or . = ' Dua')]</value>
      <webElementGuid>2a7246ff-3cdd-435c-995b-631a7f7fd58c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
